Algoritmo "Capturar nome e idade"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Rubem Oliota 
// Descrição   : Capturar nome e idade e exibir em tela
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30/05/2021
Var
// Seção de Declarações das variáveis 
nome : caractere
idade : inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("iforme seu nome :")
leia(nome)
escreval("infore sua idade :")
leia(idade)
Fimalgoritmo